name: dart_nostr
description: This is a helper package that simplify and accelerate the use of Nostr protocal in Dart/Flutter environment
version: 3.3.1
repository: https://github.com/anasfik/nostr/
issue_tracker: https://github.com/anasfik/nostr/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip340: ^0.1.0
  equatable: ^2.0.5
  convert: ^3.1.1
  crypto: ^3.0.2
  http: ^1.0.0
  meta: ^1.8.0
  bech32: ^0.2.2
  hex: ^0.2.0
  bip32_bip44: ^1.0.0
  bip39: ^1.0.6

dev_dependencies:
  lints:
  test:
